name: SCA - OWASP Dependency Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create reports folder
      run: mkdir -p odc-reports

    - name: Run OWASP Dependency Check (XML only)
      run: |
        docker run --rm \
          --user root \
          --volume "$(pwd)":/src \
          --volume "$(pwd)/odc-reports":/report \
          owasp/dependency-check:latest \
          --scan /src \
          --out /report \
          --format XML \
          --prettyPrint \
          --enableExperimental

    - name: Upload Dependency Check XML
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-xml
        path: odc-reports/

