name: SAST - Semgrep

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    # ------------------------------
    # 1. Checkout
    # ------------------------------
    - name: Checkout
      uses: actions/checkout@v4

    # ------------------------------
    # 2. Instalar Semgrep
    # ------------------------------
    - name: Install Semgrep
      run: |
        pip install semgrep

    # ------------------------------
    # 3. Rodar Semgrep CI (N√ÉO falha pipeline)
    # ------------------------------
    - name: Run Semgrep SAST
      run: |
        semgrep ci \
          --config p/default \
          --sarif --output semgrep.sarif \
          || true

    # ------------------------------
    # 4. Upload SARIF para Code Scanning
    # ------------------------------
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: semgrep.sarif

    # ------------------------------
    # 5. Artefatos opcionais
    # ------------------------------
    - name: Upload Semgrep report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report
        path: semgrep.sarif
